Models/License/LicenseAdmin.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace BLMS.Models.License
{
    public class LicenseAdmin
    {
        [Key]
        public int LicenseID { get; set; }

        //Category
        public int CategoryID { get; set; }

        [Column(TypeName = "nvarchar(150)")]
        [DisplayName("Type of License")]
        public string CategoryName { get; set; }

        //License Details
        [Column(TypeName = "nvarchar(150)")]
        [DisplayName("License Name")]
        public string LicenseName { get; set; }

        [Column(TypeName = "nvarchar(150)")]
        [DisplayName("Registration No")]
        public string RegistrationNo { get; set; }

        [Column(TypeName = "nvarchar(150)")]
        [DisplayName("Serial No")]
        public string SerialNo { get; set; }

        //Business Div
        public int DivID { get; set; }


        [Column(TypeName = "nvarchar(150)")]
        [DisplayName("Business Div")]
        public string DivName { get; set; }

        //Business Unit
        public int UnitID { get; set; }

        [Column(TypeName = "nvarchar(150)")]
        [DisplayName("Business Unit")]
        public string UnitName { get; set; }

        [DisplayName("Issued Date")]
        public string IssuedDT { get; set; }

        [DisplayName("Expired Date")]
        public string ExpiredDT { get; set; }

        //PIC 1
        [Column(TypeName = "nvarchar(150)")]
        public string PIC1StaffNo { get; set; }

        [Column(TypeName = "nvarchar(150)")]
        [DisplayName("PIC 1 Name")]
        public string PIC1Name { get; set; }

        [Column(TypeName = "nvarchar(150)")]
        [DisplayName("PIC 1 Email")]
        public string PIC1Email { get; set; }

        //PIC 2
        [Column(TypeName = "nvarchar(150)")]
        public string PIC2StaffNo { get; set; }

        [Column(TypeName = "nvarchar(150)")]
        [DisplayName("PIC 2 Name (Optional)")]
        public string PIC2Name { get; set; }

        [Column(TypeName = "nvarchar(150)")]
        [DisplayName("PIC 2 Email")]
        public string PIC2Email { get; set; }

        //PIC 3
        [Column(TypeName = "nvarchar(150)")]
        public string PIC3StaffNo { get; set; }

        [Column(TypeName = "nvarchar(150)")]
        [DisplayName("PIC 3 Name (Optional)")]
        public string PIC3Name { get; set; }

        [Column(TypeName = "nvarchar(150)")]
        [DisplayName("PIC 3 Email")]
        public string PIC3Email { get; set; }

        [Column(TypeName = "nvarchar(150)")]
        [DisplayName("Remarks")]
        public string Remarks { get; set; }

        public string UserType { get; set; }

        //Flag
        public bool isRequested { get; set; }

        public bool isApproved { get; set; }

        public bool isRegistered { get; set; }

        public bool isRenewed { get; set; }

        //Renew Remainder
        public DateTime RenewReminderDT { get; set; }

        //License File
        [Key]
        public int LicenseFileId { get; set; }

        public string LicenseFileName { get; set; }

        public string FileType { get; set; }

        public string Extension { get; set; }

        public byte[] Data { get; set; }

        //check linked data
        public int ExistData { get; set; }

        //check license had file
        public bool hasFile { get; set; }
    }
}

Controllers/LicenseAdminController.cs
using BLMS.Context;
using BLMS.Custom_Attributes;
using BLMS.CustomAttributes;
using BLMS.Enums;
using BLMS.Models.License;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BLMS.Controllers
{
    public class LicenseAdminController : Controller
    {
        readonly LicenseDBContext licenseDbContext = new LicenseDBContext();
        readonly ddlLicenseDBContext ddlLicenseDBContext = new ddlLicenseDBContext();

        private IWebHostEnvironment _env;

        #region GRIDVIEW
        [Authorize(Roles.ADMINISTRATOR, Roles.PIC)]
        [Authorize(AccessLevel.ADMINISTRATION, AccessLevel.HQ)]
        public IActionResult Index()
        {
            List<LicenseAdmin> licenseHQList = licenseDbContext.LicenseAdminGetAll().ToList();

            if (TempData["requestLicenseMessage"] != null)
            {
                ViewBag.Alert = AlertNotification.ShowAlert(Alert.Success, TempData["requestLicenseMessage"].ToString());
            }
            else if (TempData["requestRenewalMessage"] != null)
            {
                ViewBag.Alert = AlertNotification.ShowAlert(Alert.Success, TempData["requestRenewalMessage"].ToString());
            }

            return View(licenseHQList);
        }
        #endregion
    }
}

Controllers/LicenseHQController.cs
using BLMS.Context;
using BLMS.Custom_Attributes;
using BLMS.CustomAttributes;
using BLMS.Enums;
using BLMS.Models;
using BLMS.Models.License;
using BLMS.v2.Context;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MimeKit;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Net.Mail;
using System.Threading.Tasks;
using static BLMS.Helper;

namespace BLMS.Controllers
{
    public class LicenseHQController : Controller
    {
        readonly LicenseDBContext licenseDbContext = new LicenseDBContext();
        readonly ddlLicenseDBContext ddlLicenseDBContext = new ddlLicenseDBContext();
        readonly AuditLogDbContext logController = new AuditLogDbContext();

        private IWebHostEnvironment _env;

        #region GRIDVIEW
        [Authorize(Roles.ADMINISTRATOR, Roles.PIC)]
        [Authorize(AccessLevel.ADMINISTRATION, AccessLevel.HQ)]
        public IActionResult Index()
        {
            List<LicenseHQ> licenseHQList = licenseDbContext.LicenseHQGetAll().ToList();

            if (TempData["requestLicenseMessage"] != null)
            {
                ViewBag.Alert = AlertNotification.ShowAlert(Alert.Success, TempData["requestLicenseMessage"].ToString());
            }
            else if (TempData["requestRenewalMessage"] != null)
            {
                ViewBag.Alert = AlertNotification.ShowAlert(Alert.Success, TempData["requestRenewalMessage"].ToString());
            }

            return View(licenseHQList);
        }
        #endregion

        #region VIEW REQUEST LICENSE
        [Authorize(Roles.ADMINISTRATOR, Roles.PIC)]
        [Authorize(AccessLevel.ADMINISTRATION, AccessLevel.HQ)]
        [NoDirectAccess]
        public ActionResult DetailRequest(int id)
        {
            LicenseHQ licenseHQ = licenseDbContext.GetLicenseHQByID(id);

            if (licenseHQ == null)
            {
                return NotFound();
            }

            return View(licenseHQ);
        }
        #endregion

        #region VIEW REGISTER LICENSE
        [Authorize(Roles.ADMINISTRATOR, Roles.PIC)]
        [Authorize(AccessLevel.ADMINISTRATION, AccessLevel.HQ)]
        [NoDirectAccess]
        public ActionResult DetailRegister(int id)
        {
            LicenseHQ licenseHQ = licenseDbContext.GetLicenseHQByID(id);

            if (licenseHQ == null)
            {
                return NotFound();
            }

            return View(licenseHQ);
        }
        #endregion

        #region REQUEST
        [Authorize(Roles.ADMINISTRATOR, Roles.PIC)]
        [Authorize(AccessLevel.ADMINISTRATION, AccessLevel.HQ)]
        public ActionResult RequestLicense()
        {
            //ddlCategory
            List<LicenseHQ> categoryLicenseHQList = ddlLicenseDBContext.ddlCategoryLicenseHQ().ToList();
            categoryLicenseHQList.Insert(0, new LicenseHQ { CategoryID = 0, CategoryName = "Please Select Type of License" });
            ViewBag.ListofCategory = categoryLicenseHQList;

            //ddlBusinessDiv
            List<LicenseHQ> businessDivLicenseHQList = ddlLicenseDBContext.ddlBusinessDivLicenseHQ().ToList();
            businessDivLicenseHQList.Insert(0, new LicenseHQ { DivID = 0, DivName = "Please Select Business Division" });
            ViewBag.ListofBusinessDiv = businessDivLicenseHQList;

            //ddlBusinessUnit
            List<LicenseHQ> businessUnitLicenseHQList = ddlLicenseDBContext.ddlBusinessUnitLicenseHQ().ToList();
            businessUnitLicenseHQList.Insert(0, new LicenseHQ { UnitID = 0, UnitName = "Please Select Business Unit" });
            ViewBag.ListofBusinessUnit = businessUnitLicenseHQList;

            //ddlPIC2
            List<LicenseHQ> PIC2LicenseHQList = ddlLicenseDBContext.ddlPIC2LicenseHQ().ToList();
            PIC2LicenseHQList.Insert(0, new LicenseHQ { PIC2StaffNo = "-", PIC2Name = "Please Select PIC 2 Name" });
            ViewBag.ListofPIC2 = PIC2LicenseHQList;

            //ddlPIC3
            List<LicenseHQ> PIC3LicenseHQList = ddlLicenseDBContext.ddlPIC3LicenseHQ().ToList();
            PIC3LicenseHQList.Insert(0, new LicenseHQ { PIC3StaffNo = "-", PIC3Name = "Please Select PIC 3 Name" });
            ViewBag.ListofPIC3 = PIC3LicenseHQList;

            return View();
        }

        // POST: LicenseHQController/Request
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RequestLicense([Bind] LicenseHQ licenseHQ)
        {
            string UserName = User.Identity.Name;

            try
            {
              
                List<LicenseHQ> categoryLicenseHQList, businessDivLicenseHQList, businessUnitLicenseHQList, PIC2LicenseHQList, PIC3LicenseHQList;

                if (string.IsNullOrEmpty(licenseHQ.PIC1Name))
                {
                    ModelState.AddModelError("", "Your session has been expired. Please login again.");
                    ViewBag.Alert = AlertNotification.ShowAlert(Alert.Warning, "Your session has been expired. Please login again.");
                }
                else if (string.IsNullOrEmpty(licenseHQ.LicenseName) && licenseHQ.CategoryID == 0 && licenseHQ.DivID == 0 && licenseHQ.UnitID == 0)
                {
                    ModelState.AddModelError("", "Please type License Name");
                    ModelState.AddModelError("", "Please select License Type");
                    ModelState.AddModelError("", "Please select Business Division");
                    ModelState.AddModelError("", "Please select Business Unit");
                    ViewBag.Alert = AlertNotification.ShowAlertAll(Alert.WarningFour, "Please type License Name", "Please select License Type", "Please select Business Division", "Please select Business Unit");
                }
                else if (string.IsNullOrEmpty(licenseHQ.LicenseName) && licenseHQ.CategoryID == 0 && licenseHQ.DivID == 0)
                {
                    ModelState.AddModelError("", "Please type License Name");
                    ModelState.AddModelError("", "Please select License Type");
                    ModelState.AddModelError("", "Please select Business Division");
                    ViewBag.Alert = AlertNotification.ShowAlertAll(Alert.WarningThree, "Please type License Name", "Please select License Type", "Please select Business Division", "");
                }
                else if (string.IsNullOrEmpty(licenseHQ.LicenseName) && licenseHQ.CategoryID == 0 && licenseHQ.UnitID == 0)
                {
                    ModelState.AddModelError("", "Please type License Name");
                    ModelState.AddModelError("", "Please select License Type");
                    ModelState.AddModelError("", "Please select Business Unit");
                    ViewBag.Alert = AlertNotification.ShowAlertAll(Alert.WarningThree, "Please type License Name", "Please select License Type", "Please select Business Unit", "");
                }
                else if (licenseHQ.CategoryID == 0 && licenseHQ.DivID == 0 && licenseHQ.UnitID == 0)
                {
                    ModelState.AddModelError("", "Please select License Type");
                    ModelState.AddModelError("", "Please select Business Division");
                    ModelState.AddModelError("", "Please select Business Unit");
                    ViewBag.Alert = AlertNotification.ShowAlertAll(Alert.WarningThree, "Please select License Type", "Please select Business Division", "Please select Business Unit", "");
                }
                else if (string.IsNullOrEmpty(licenseHQ.LicenseName) && licenseHQ.CategoryID == 0)
                {
                    ModelState.AddModelError("", "Please type License Name");
                    ModelState.AddModelError("", "Please select License Type");
                    ViewBag.Alert = AlertNotification.ShowAlertAll(Alert.WarningTwo, "Please type License Name", "Please select License Type", "", "");
                }
                else if (string.IsNullOrEmpty(licenseHQ.LicenseName) && licenseHQ.DivID == 0)
                {
                    ModelState.AddModelError("", "Please type License Name");
                    ModelState.AddModelError("", "Please select Business Division");
                    ViewBag.Alert = AlertNotification.ShowAlertAll(Alert.WarningTwo, "Please type License Name", "Please select Business Division", "", "");
                }
                else if (string.IsNullOrEmpty(licenseHQ.LicenseName) && licenseHQ.UnitID == 0)
                {
                    ModelState.AddModelError("", "Please type License Name");
                    ModelState.AddModelError("", "Please select Business Unit");
                    ViewBag.Alert = AlertNotification.ShowAlertAll(Alert.WarningTwo, "Please type License Name", "Please select Business Unit", "", "");
                }
                else if (licenseHQ.CategoryID == 0 && licenseHQ.DivID == 0)
                {
                    ModelState.AddModelError("", "Please select License Type");
                    ModelState.AddModelError("", "Please select Business Division");
                    ViewBag.Alert = AlertNotification.ShowAlertAll(Alert.WarningTwo, "Please select License Type", "Please select Business Division", "", "");
                }
                else if (licenseHQ.CategoryID == 0 && licenseHQ.UnitID == 0)
                {
                    ModelState.AddModelError("", "Please select License Type");
                    ModelState.AddModelError("", "Please select Business Unit");
                    ViewBag.Alert = AlertNotification.ShowAlertAll(Alert.WarningTwo, "Please select License Type", "Please select Business Unit", "", "");
                }
                else if (licenseHQ.DivID == 0 && licenseHQ.UnitID == 0)
                {
                    ModelState.AddModelError("", "Please select Business Division");

Views/LicenseAdmin/Index.cshtml
@model IEnumerable<BLMS.Models.License.LicenseAdmin>

@{
    ViewData["Title"] = "Application Tracking";
}

<section class="section align-baseline">
    <!-- Grid row -->
    <div class="row">

        <!-- Grid column -->
        <div class="col-md-12">
            <div class="card card-cascade cascading-admin-card user-card">
                <!-- Card Data -->
                <div class="admin-up d-flex justify-content-start">
                    <i class="fas fa fa-chart-line info-color py-4 mr-3 z-depth-2"></i>
                    <div class="data">
                        <h5 class="font-weight-bold dark-grey-text">
                            Application Tracking
                        </h5>
                    </div>
                </div>
                <!-- Card Data -->
                <!-- Card content -->
                <div class="card-body card-body-cascade">
                    <!-- Grid row -->
                    <div class="row">
                        <div class="col-lg-12">
                            <div id="alert" class="form-group">
                                @Html.Raw(@ViewBag.Alert)
                            </div>

                            <div class="table table-wrapper table-responsive-sm">
                                <!--Table-->
                                <table id="LicenseAdmin" class="table table-bordered table-hover mb-0">
                                    <!-- Table head -->
                                    <thead class="morpheus-den-gradient text-white">
                                        <tr>
                                            <th class="text-sm font-weight-bold align-text-top col-md-2">
                                                @Html.DisplayNameFor(model => model.UnitName)
                                            </th>
                                            <th class="text-sm font-weight-bold align-text-top col-md-2">
                                                @Html.DisplayNameFor(model => model.LicenseName)
                                            </th>
                                            <th class="text-sm font-weight-bold align-text-top col-md-1">File</th>
                                            <th class="text-sm font-weight-bold align-text-top col-md-2">
                                                @Html.DisplayNameFor(model => model.CategoryName)
                                            </th>
                                            <th class="text-sm font-weight-bold align-text-top col-md-2">Person in Charge</th>
                                            <th class="text-sm font-weight-bold align-text-top col-md-1">Issued & Expired Date</th>
                                            <th class="text-sm font-weight-bold align-text-top col-md-1">User Type</th>
                                            <th class="text-sm font-weight-bold align-text-top col-md-1">Status</th>
                                        </tr>
                                    </thead>
                                    <!-- Table head -->
                                    <!-- Table body -->
                                    <tbody>
                                        @foreach (var item in Model)
                                        {
                                        <tr>
                                            <td class="text-sm">
                                                @Html.DisplayFor(modelItem => item.UnitName)
                                            </td>
                                            <td class="text-sm">
                                                @if (item.isRequested == true | item.isApproved == true)
                                                {
                                                    <a href="@Url.Action("DetailRequest", "LicenseHQ", new {id=item.LicenseID})" class="font-weight-bold">
                                                        @Html.DisplayFor(modelItem => item.LicenseName)
                                                    </a>

                                                    <br/><br/>

                                                    @if (item.isApproved == true)
                                                    {
                                                        <a class="btn btn-outline-success btn-rounded btn-sm px-2" title="Click to Register" href="@Url.Action("RegisterLicense", "LicenseAdmin", new {id=item.DivID})">
                                                            Click to Register
                                                        </a>
                                                    }
                                                }
                                                else
                                                {
                                                    <a href="@Url.Action("DetailRegister", "LicenseHQ", new {id=item.LicenseID})" class="font-weight-bold">
                                                        @Html.DisplayFor(modelItem => item.LicenseName)
                                                    </a>
                                                }
                                            </td>
                                            <td class="text-center">
                                                @if (item.hasFile == true)
                                                {
                                                    <a class="btn btn-outline-primary btn-rounded btn-sm px-2" type="button" title="Download File" asp-controller="LicenseAdmin" asp-action="DownloadLicenseFile" asp-route-id="@item.LicenseID">
                                                        <i class="fas fa-file-alt mt-0"></i> Download
                                                    </a>
                                                }
                                            </td>
                                            <td class="text-sm">
                                                @Html.DisplayFor(modelItem => item.CategoryName)
                                            </td>
                                            <td class="text-sm">
                                                @if (string.IsNullOrEmpty(item.PIC1Name))
                                                {

                                                }
                                                else
                                                {
                                                    <label class="font-weight-bold">PIC 1:</label>
                                                    <br />
                                                    @Html.DisplayFor(modelItem => item.PIC1Name)
                                                    <br /><br />
                                                }

                                                @if (string.IsNullOrEmpty(item.PIC2Name))
                                                {

                                                }
                                                else
                                                {
                                                    <label class="font-weight-bold">PIC 2:</label>
                                                    <br />
                                                    @Html.DisplayFor(modelItem => item.PIC2Name)
                                                    <br /><br />
                                                }

                                                @if (string.IsNullOrEmpty(item.PIC3Name))
                                                {

                                                }
                                                else
                                                {
                                                    <label class="font-weight-bold">PIC 3:</label>
                                                    <br />
                                                    @Html.DisplayFor(modelItem => item.PIC3Name)
                                                }
                                            </td>
                                            <td class="text-sm text-center">
                                                @if (string.IsNullOrEmpty(item.IssuedDT))
                                                {

                                                }
                                                else
                                                {
                                                    <label class="font-weight-bold">Issued Date:</label>
                                                    @Html.DisplayFor(modelItem => item.IssuedDT)
                                                    <br /><br />
                                                }

                                                @if (string.IsNullOrEmpty(item.ExpiredDT))
                                                {

                                                }
                                                else
                                                {
                                                    <label class="font-weight-bold">Expired Date:</label>
                                                    @Html.DisplayFor(modelItem => item.ExpiredDT)
                                                }
                                            </td>
                                            <td class="text-sm">
                                                @Html.DisplayFor(modelItem => item.UserType)
                                            </td>
                                            <td class="text-center">
                                                @if (item.isRequested == true)
                                                {
                                                    <button name="button" class="btn btn-outline-warning btn-rounded btn-sm px-2" disabled>
                                                        <i class="fas fa-spinner mt-0"></i> Requested
                                                    </button>
                                                }
                                                else if (item.isApproved == true)
                                                {
                                                    <button name="button" class="btn btn-outline-info btn-rounded btn-sm px-2" disabled>
                                                        <i class="fas fa-clock mt-0"></i> Approved
                                                    </button>
                                                }
                                                else if (item.isRegistered == true)
                                                {
                                                    <button name="button" class="btn btn-outline-success btn-rounded btn-sm px-2" disabled>
                                                        <i class="fas fa-check mt-0"></i> Registered
                                                    </button>
                                                }
                                                else if (item.isRenewed == true)
                                                {
                                                    <button name="button" class="btn btn-outline-warning btn-rounded btn-sm px-2" disabled>
                                                        <i class="fas fa-exclamation mt-0"></i> Renewed
                                                    </button>
                                                }

                                                @if ((item.RenewReminderDT.Date - DateTime.Now.Date).Days > 0 | item.RenewReminderDT.ToString() == "9999-12-31 00:00:00.000")
                                                {
                                                    <button name="button" class="btn btn-outline-success btn-rounded btn-sm px-2" disabled>
                                                        <i class="fas fa-thumbs-up mt-0"></i> Active
                                                    </button>
                                                }
                                                else
                                                {
                                                    <button name="button" class="btn btn-outline-danger btn-rounded btn-sm px-2" disabled>
                                                        <i class="fas fa-thumbs-down mt-0"></i> Not Active
                                                    </button>
                                                }
                                            </td>
                                        </tr>
                                        }
                                    </tbody>
                                    <!-- Table body -->
                                </table>
                                <!-- Table -->
                            </div>
                        </div>
                    </div>
                    <!-- Grid row -->
                </div>
                <!-- Card content -->
            </div>
        </div>
    </div>
</section>

@section Scripts {
    <script>
        $(document).ready(function () {
            $('#LicenseAdmin').DataTable();
            $('.dataTables_length').addClass('bs-select');
        });

        //auto hide viewbag.alert
        $(document).ready(function () {
            setTimeout(function () {
                $("#alert").fadeOut();
            }, 3000);
        });
    </script>

    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}