Controllers/CategoryController.cs
using BLMS.Context;
using BLMS.Custom_Attributes;
using BLMS.CustomAttributes;
using BLMS.Enums;
using BLMS.Models.Admin;
using BLMS.v2.Context;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using static BLMS.Helper;

namespace BLMS.Controllers
{
    public class CategoryController : Controller
    {
        readonly AdminDBContext dbContext = new AdminDBContext();
        readonly AuditLogDbContext logController = new AuditLogDbContext();

        #region GRIDVIEW
        [Authorize(Roles.ADMINISTRATOR)]
        [Authorize(AccessLevel.ADMINISTRATION)]
        public ActionResult Index()
        {
            List<Category> CategoryList = dbContext.CategoryGetAll().ToList();

            if (TempData["createMessage"] != null)
            {
                ViewBag.Alert = AlertNotification.ShowAlert(Alert.Success, TempData["createMessage"].ToString());
            }
            else if (TempData["editMessage"] != null)
            {
                ViewBag.Alert = AlertNotification.ShowAlert(Alert.Success, TempData["editMessage"].ToString());
            }
            else if (TempData["deleteMessage"] != null)
            {
                ViewBag.Alert = AlertNotification.ShowAlert(Alert.Delete, TempData["deleteMessage"].ToString());
            }

            return View(CategoryList);
        }
        #endregion

        #region CREATE
        [Authorize(Roles.ADMINISTRATOR)]
        [Authorize(AccessLevel.ADMINISTRATION)]
        [NoDirectAccess]
        public ActionResult Create()
        {
            return View();
        }

        // POST: CategoryController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind] Category category, string UserName)
        {
            try
            {
                UserName = HttpContext.User.Identity.Name;

                if (string.IsNullOrEmpty(category.CategoryName) && string.IsNullOrEmpty(category.Description))
                {
                    ModelState.AddModelError("", "Please type License Type");
                    ModelState.AddModelError("", "Please type License Description");
                    ViewBag.Alert = AlertNotification.ShowAlertAll(Alert.WarningTwo, "Please type License Type", "Please type License Description", "", "");
                }
                else if (string.IsNullOrEmpty(category.CategoryName))
                {
                    ModelState.AddModelError("", "Please type License Type");
                    ViewBag.Alert = AlertNotification.ShowAlert(Alert.Warning, "Please type License Type");
                }
                else if (string.IsNullOrEmpty(category.Description))
                {
                    ModelState.AddModelError("", "Please type License Description");
                    ViewBag.Alert = AlertNotification.ShowAlert(Alert.Warning, "Please type License Description");
                }
                if (ModelState.IsValid)
                {
                    string CategoryName = category.CategoryName;

                    Category checkCategory = dbContext.CheckCategoryByName(CategoryName);

                    if (checkCategory.ExistData == 1)
                    {
                        ViewBag.Alert = AlertNotification.ShowAlert(Alert.Danger, string.Format("{0} already existed in BLMS database!", CategoryName));
                        return View(category);
                    }
                    else
                    {
                        dbContext.AddCategory(category, UserName);
                        TempData["createMessage"] = string.Format("{0} has been successfully created!", CategoryName);
                        return RedirectToAction("Index");
                    }
                }

                return View(category);
            }
            catch(Exception ex)
            {
                string path = "CATEGORY";

                System.Diagnostics.StackTrace trace = new System.Diagnostics.StackTrace(ex, true);

                string msg = ex.Message;
                string method = trace.GetFrame((trace.FrameCount - 1)).GetMethod().ToString();
                Int32 lineNumber = trace.GetFrame((trace.FrameCount - 1)).GetFileLineNumber();

                logController.AddErrorLog(path, method, lineNumber, msg, UserName);

                return View();
            }
        }
        #endregion

        #region EDIT
        [Authorize(Roles.ADMINISTRATOR)]
        [Authorize(AccessLevel.ADMINISTRATION)]
        [NoDirectAccess]
        public ActionResult Edit(int id)
        {
            Category category = dbContext.GetCategoryByID(id);

            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: CategoryController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, [Bind] Category category, string UserName)
        {
            try
            {
                UserName = HttpContext.User.Identity.Name;

                if (string.IsNullOrEmpty(category.CategoryName) && string.IsNullOrEmpty(category.Description))
                {
                    ModelState.AddModelError("", "Please type License Type");
                    ModelState.AddModelError("", "Please type License Description");
                    ViewBag.Alert = AlertNotification.ShowAlertAll(Alert.WarningTwo, "Please type License Type", "Please type License Description", "", "");
                }
                else if (string.IsNullOrEmpty(category.CategoryName))
                {
                    ModelState.AddModelError("", "Please type License Type");
                    ViewBag.Alert = AlertNotification.ShowAlert(Alert.Warning, "Please type License Type");
                }
                else if (string.IsNullOrEmpty(category.Description))
                {
                    ModelState.AddModelError("", "Please type License Description");
                    ViewBag.Alert = AlertNotification.ShowAlert(Alert.Warning, "Please type License Description");
                }
                if (ModelState.IsValid)
                {
                    string CategoryName = category.CategoryName;
                    string oldCategoryName = category.OldCategoryName;
                    string oldDesc = category.OldDesc;

                    Category checkCategory = dbContext.CheckCategoryByName(CategoryName);

                    if (checkCategory.ExistData == 1 && CategoryName != oldCategoryName && category.Description == oldDesc)
                    {
                        ViewBag.Alert = AlertNotification.ShowAlert(Alert.Danger, string.Format("{0} already existed in BLMS database!", CategoryName));
                        return View(category);
                    }
                    else if (checkCategory.ExistData == 1 && CategoryName != oldCategoryName && category.Description != oldDesc)
                    {
                        ViewBag.Alert = AlertNotification.ShowAlert(Alert.Danger, string.Format("{0} already existed in BLMS database!", CategoryName));
                        return View(category);
                    }
                    else if (checkCategory.ExistData == 1 && CategoryName == oldCategoryName && category.Description == oldDesc)
                    {
                        dbContext.EditCategory(category, UserName);
                        return RedirectToAction("Index");
                    }
                    else if (checkCategory.ExistData == 1 && CategoryName == oldCategoryName && category.Description != oldDesc)
                    {
                        dbContext.EditCategory(category, UserName);
                        TempData["editMessage"] = string.Format("{0} has been successfully edited!", category.CategoryName);
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        dbContext.EditCategory(category, UserName);
                        TempData["editMessage"] = string.Format("{0} has been successfully edited!", category.CategoryName);
                        return RedirectToAction("Index");
                    }
                }

                return View(dbContext);
            }
            catch
            {
                return View();
            }
        }
        #endregion

        #region DELETE
        [Authorize(Roles.ADMINISTRATOR)]
        [Authorize(AccessLevel.ADMINISTRATION)]
        public JsonResult Delete(int Id)
        {
            string UserName = User.Identity.Name;

            try
            {
                Category category = dbContext.GetCategoryByID(Id);

                dbContext.DeleteCategory(Id, category.CategoryName, UserName);
                TempData["deleteMessage"] = string.Format("{0} has been successfully deleted!", category.CategoryName);

                return Json(new { status = "Success" });
            }
            catch(Exception ex)
            {
                string path = "CATEGORY";

                System.Diagnostics.StackTrace trace = new System.Diagnostics.StackTrace(ex, true);

                string msg = ex.Message;
                string method = trace.GetFrame((trace.FrameCount - 1)).GetMethod().ToString();
                Int32 lineNumber = trace.GetFrame((trace.FrameCount - 1)).GetFileLineNumber();

                logController.AddErrorLog(path, method, lineNumber, msg, UserName);

                return Json(new { status = "Fail" }); 
            }
        }
        #endregion
    }
}

Controllers/CertBodyController.cs
using BLMS.Context;
using BLMS.Custom_Attributes;
using BLMS.CustomAttributes;
using BLMS.Enums;
using BLMS.Models.Admin;
using BLMS.v2.Context;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using static BLMS.Helper;

namespace BLMS.Controllers
{
    public class CertBodyController : Controller
    {
        readonly AdminDBContext dbContext = new AdminDBContext();
        readonly AuditLogDbContext logController = new AuditLogDbContext();

        #region GRIDVIEW
        [Authorize(Roles.ADMINISTRATOR)]
        [Authorize(AccessLevel.ADMINISTRATION)]
        public IActionResult Index()
        {
            List<CertBody> CertbodyList = dbContext.CertBodyGetAll().ToList();

            if (TempData["createMessage"] != null)
            {
                ViewBag.Alert = AlertNotification.ShowAlert(Alert.Success, TempData["createMessage"].ToString());
            }
            else if (TempData["editMessage"] != null)
            {
                ViewBag.Alert = AlertNotification.ShowAlert(Alert.Success, TempData["editMessage"].ToString());
            }
            else if (TempData["deleteMessage"] != null)
            {
                ViewBag.Alert = AlertNotification.ShowAlert(Alert.Delete, TempData["deleteMessage"].ToString());
            }

            return View(CertbodyList);
        }
        #endregion

        #region CREATE
        [Authorize(Roles.ADMINISTRATOR)]
        [Authorize(AccessLevel.ADMINISTRATION)]
        [NoDirectAccess]
        public ActionResult Create()
        {
            return View();
        }

        // POST: BusinessDivController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind] CertBody certBody)
        {
            string UserName = HttpContext.User.Identity.Name;

            try
            {
               

                if (string.IsNullOrEmpty(certBody.CertBodyName))
                {
                    ModelState.AddModelError("", "Please type Certificate Body");
                    ViewBag.Alert = AlertNotification.ShowAlert(Alert.Warning, "Please type Certificate Body");
                }
                else if (ModelState.IsValid)
                {
                    CertBody checkCertBody = dbContext.CheckCertBodyByName(certBody.CertBodyName);

                    if (checkCertBody.ExistData == 1)
                    {
                        ViewBag.Alert = AlertNotification.ShowAlert(Alert.Danger, string.Format("{0} already existed in BLMS database!", certBody.CertBodyName));
                        return View(certBody);
                    }
                    else
                    {
                        dbContext.AddCertBody(certBody, UserName);
                        TempData["createMessage"] = string.Format("{0} has been successfully created!", certBody.CertBodyName);
                        return RedirectToAction("Index");
                    }
                }

                return View(certBody);
            }
            catch(Exception ex)
            {
                string path = "CERTIFICATE BODY";

                System.Diagnostics.StackTrace trace = new System.Diagnostics.StackTrace(ex, true);

                string msg = ex.Message;
                string method = trace.GetFrame((trace.FrameCount - 1)).GetMethod().ToString();
                Int32 lineNumber = trace.GetFrame((trace.FrameCount - 1)).GetFileLineNumber();

                logController.AddErrorLog(path, method, lineNumber, msg, UserName);


                return View();
            }
        }
        #endregion

        #region EDIT
        [Authorize(Roles.ADMINISTRATOR)]
        [Authorize(AccessLevel.ADMINISTRATION)]
        [NoDirectAccess]
        public ActionResult Edit(int id)
        {
            CertBody certBody = dbContext.GetCertBodyByID(id);

            if (certBody == null)
            {
                return NotFound();
            }

            return View(certBody);
        }

        // POST: BusinessDivController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, [Bind] CertBody certBody)
        {
            string UserName = HttpContext.User.Identity.Name;

            try
            {
                

                if (string.IsNullOrEmpty(certBody.CertBodyName))
                {
                    ModelState.AddModelError("", "Please type Certificate Body");
                    ViewBag.Alert = AlertNotification.ShowAlert(Alert.Warning, "Please type Certificate Body");
                }
                else if (ModelState.IsValid)
                {
                    CertBody checkCertBody = dbContext.CheckCertBodyByName(certBody.CertBodyName);

                    if (checkCertBody.ExistData == 1 && certBody.CertBodyName != certBody.OldCertBodyName)
                    {
                        ViewBag.Alert = AlertNotification.ShowAlert(Alert.Danger, string.Format("{0} already existed in BLMS database!", certBody.CertBodyName));
                        return View(certBody);
                    }
                    else if (checkCertBody.ExistData == 1 && certBody.CertBodyName == certBody.OldCertBodyName)
                    {
                        dbContext.EditCertBody(certBody, UserName);
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        dbContext.EditCertBody(certBody, UserName);
                        TempData["editMessage"] = string.Format("{0} has been successfully edited!", certBody.CertBodyName);
                        return RedirectToAction("Index");
                    }
                }

                return View(dbContext);
            }
            catch(Exception ex)
            {
                string path = "CERTIFICATE BODY";

                System.Diagnostics.StackTrace trace = new System.Diagnostics.StackTrace(ex, true);

                string msg = ex.Message;
                string method = trace.GetFrame((trace.FrameCount - 1)).GetMethod().ToString();
                Int32 lineNumber = trace.GetFrame((trace.FrameCount - 1)).GetFileLineNumber();

                logController.AddErrorLog(path, method, lineNumber, msg, UserName);

                return View(); 
            }
        }
        #endregion

        #region DELETE
        [Authorize(Roles.ADMINISTRATOR)]
        [Authorize(AccessLevel.ADMINISTRATION)]
        public JsonResult Delete(int Id)
        {
            string UserName = User.Identity.Name;

            try
            {
                CertBody certBody = dbContext.GetCertBodyByID(Id);

                dbContext.DeleteCertBody(Id, certBody.CertBodyName, UserName);
                TempData["deleteMessage"] = string.Format("{0} has been deleted from BLMS database!", certBody.CertBodyName);

                return Json(new { status = "Success" });
            }
            catch(Exception ex)
            {
                string path = "CERTIFICATE BODY";

                System.Diagnostics.StackTrace trace = new System.Diagnostics.StackTrace(ex, true);

                string msg = ex.Message;
                string method = trace.GetFrame((trace.FrameCount - 1)).GetMethod().ToString();
                Int32 lineNumber = trace.GetFrame((trace.FrameCount - 1)).GetFileLineNumber();

                logController.AddErrorLog(path, method, lineNumber, msg, UserName);


                return Json(new { status = "Fail" });
            }
        }
        #endregion
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>BLMS - @ViewData["Title"]</title>
    <link href="~/fontawesome/all.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/mdb/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/mdb/css/mdb.min.css" rel="stylesheet" />
    <link href="~/mdb/css/style.min.css" rel="stylesheet" />
    <link href="~/mdb/css/addons/datatables.min.css" rel="stylesheet" />
    <link href="~/mdb/css/addons/datatables-select.min.css" rel="stylesheet" />
    <link href="~/css/bootstrap-datepicker.min.css" rel="stylesheet" />
</head>
<body class="fixed-sn white-skin">
    <!-- Main Navigation -->
    <header>
        <!-- Sidebar navigation -->
        <div id="slide-out" class="side-nav sn-bg-4 fixed">
            <ul class="custom-scrollbar">
                <!-- Logo -->
                <li class="logo-sn waves-effect py-4">
                    <div class="text-center">
                        <a href="@Url.Action("Index", "Home")" class="pl-0"><img src="~/img/BLMS-no-bg.png" /></a>
                    </div>
                </li>

                <!-- Side navigation links -->
                <li>
                    <ul class="collapsible collapsible-accordion">
                        <li>
                            <a href="#" class="collapsible-header waves-effect text-md">
                                <i class="w-fa fas fa-tachometer-alt"></i>BLMS Dashboard
                            </a>
                        </li>
                        <li>
                            <a class="collapsible-header waves-effect arrow-r">
                                <i class="w-fa fas fa-industry"></i>Site User<i class="fas fa-angle-down rotate-icon"></i>
                            </a>
                            <div class="collapsible-body">
                                <ul>
                                    <li>
                                        <a href="@Url.Action("Index", "LicenseSite")" class="waves-effect">License Listing</a>
                                    </li>
                                    <li>
                                        <a href="@Url.Action("Register", "LicenseSite")" class="waves-effect">License Register</a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                        <li>
                            <a class="collapsible-header waves-effect arrow-r">
                                <i class="w-fa fas fa-building"></i>HQ User<i class="fas fa-angle-down rotate-icon"></i>
                            </a>
                            <div class="collapsible-body">
                                <ul>
                                    <li>
                                        <a href="@Url.Action("Index", "LicenseHQ")" class="waves-effect">License Listing</a>
                                    </li>
                                    <li>
                                        <a href="@Url.Action("RequestLicense", "LicenseHQ")" class="waves-effect">License Request</a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                        <li>
                            <a href="http://10.49.45.41/Reports/browse/BLMS" target="_blank" class="collapsible-header waves-effect arrow-r">
                                <i class="w-fa fab fa fa-chart-bar"></i>Reporting
                            </a>
                        </li>
                        <li>
                            <a class="collapsible-header waves-effect arrow-r">
                                <i class="w-fa fas fa-book"></i>Supporting Documents<i class="fas fa-angle-down rotate-icon"></i>
                            </a>
                            <div class="collapsible-body">
                                <ul>
                                    <li>
                                        <a href="@Url.Action("Index", "SOP")" class="waves-effect">SOP's & Guidelines</a>
                                    </li>
                                    <li>
                                        <a href="@Url.Action("Index", "Authority")" class="waves-effect">Authority Link</a>
                                    </li>
                                    <li>
                                        <a href="@Url.Action("Index", "CompetentPersonnel")" class="waves-effect">Competent Personnel</a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                        <li>
                            <a class="collapsible-header waves-effect arrow-r">
                                <i class="w-fa fas fa-user"></i>Administration Module<i class="fas fa-angle-down rotate-icon"></i>
                            </a>
                            <div class="collapsible-body">
                                <ul>
                                    <li>
                                        <ul class="collapsible collapsible-accordion mt-0">
                                            <li>
                                                <a class="collapsible-header waves-effect arrow-r">
                                                    <i class="w-fa fas fa fa-registered"></i>Registration<i class="fas fa-angle-down rotate-icon"></i>
                                                </a>
                                                <div class="collapsible-body">
                                                    <ul>
                                                        <li>
                                                            <a href="@Url.Action("Index", "BusinessDiv")" class="waves-effect">Business Division</a>
                                                        </li>
                                                        <li>
                                                            <a href="@Url.Action("Index", "BusinessUnit")" class="waves-effect">Business Unit</a>
                                                        </li>
                                                        <li>
                                                            <a href="@Url.Action("Index", "CertBody")" class="waves-effect">Certificate Body</a>
                                                        </li>
                                                        <li>
                                                            <a href="@Url.Action("Index", "Category")" class="waves-effect">License Type</a>
                                                        </li>
                                                        <li>
                                                            <a href="@Url.Action("Index", "PIC")" class="waves-effect">Person in Charge</a>
                                                        </li>
                                                        <li>
                                                            <a href="@Url.Action("Index", "UserRole")" class="waves-effect">User Role</a>
                                                        </li>
                                                    </ul>
                                                </div>
                                            </li>
                                        </ul>
                                    </li>
                                    <li>
                                        <a href="@Url.Action("Index", "LicenseAdmin")" class="waves-effect"><i class="w-fa fas fa fa-chart-line"></i>Application Tracking</a>
                                    </li>
                                    <li>
                                        <a href="@Url.Action("Index", "AuditErrorLog")" class="waves-effect"><i class="w-fa fas fa fa-list-alt"></i>Audit & Error Log</a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                    </ul>
                </li>
                <!-- Side navigation links -->
            </ul>
            <div class="sidenav-bg mask-strong"></div>
        </div>
        <!-- Sidebar navigation -->
        <!-- Navbar -->
        <nav class="navbar fixed-top navbar-expand-lg scrolling-navbar double-nav">
            <!-- SideNav slide-out button -->
            <div class="float-left">
                <a href="#" data-activates="slide-out" class="button-collapse"><i class="fas fa-bars"></i></a>
            </div>

            <!-- Breadcrumb -->
            <div class="breadcrumb-dn mr-auto font-weight-bold">
                <p>BUSINESS LICENSE MANAGEMENT SYSTEM (BLMS)</p>
            </div>

            <!-- Navbar links -->
            <ul class="nav navbar-nav nav-flex-icons ml-auto">
                <!-- Dropdown -->

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle waves-effect" href="#" id="userDropdown" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        <span class="clearfix d-none d-sm-inline-block font-weight-bold">@User.Identity.Name @ViewBag.UserRole </span>
                        <img src="https://mdbootstrap.com/img/Photos/Avatars/avatar-5.jpg" class="rounded-circle z-depth-0"
                             alt="avatar image" height="25">
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                        <a class="dropdown-item" href="@Url.Action("Index", "Profile")">My profile</a>
                        <a class="dropdown-item" href="#">Log Out</a>
                    </div>
                </li>
            </ul>
            <!-- Navbar links -->
        </nav>
        <!-- Navbar -->
    </header>

    <main role="main" class="pb-3">
        <div class="container-fluid">
            @RenderBody()
        </div>
    </main>

    <!-- Footer -->
    <footer class="text-center text-lg-start bg-light text-muted">
        <!-- Copyright -->
        <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
            Copyright © 2021 -
            <a class="text-reset fw-bold" href="https://www.uemedgenta.com/">UEM Edgenta Berhad</a>
        </div>
        <!-- Copyright -->
    </footer>
    <!-- Footer -->

    <script src="~/mdb/js/jquery-3.4.1.min.js"></script>
    <script src="~/mdb/js/popper.min.js"></script>
    <script src="~/mdb/js/bootstrap.min.js"></script>
    <script src="~/mdb/js/mdb.min.js"></script>
    <script src="~/mdb/js/addons/datatables.min.js"></script>
    <script src="~/mdb/js/addons/datatables-select.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/bootstrap-datepicker.js"></script>
    <script src="~/mdb/js/modules/picker-date.js"></script>
    <script src="~/mdb/js/modules/picker-time.js"></script>
    <script src="~/mdb/js/modules/picker.js"></script>

    <script>
        // SideNav Initialization
        $(".button-collapse").sideNav();

        var container = document.querySelector('.custom-scrollbar');
        var ps = new PerfectScrollbar(container, {
            wheelSpeed: 2,
            wheelPropagation: true,
            minScrollbarLength: 20
        });
    </script>

    @await RenderSectionAsync("Scripts", required: false)
    @await RenderSectionAsync("CSS", required: false)
</body>
</html>