Models/SOP/Authority.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BLMS.Models.SOP
{
    public class Authority
    {
        [Key]
        public int AuthorityID { get; set; }

        [DisplayName("Authority Link")]
        public string AuthorityLink { get; set; }

        [DisplayName("Authority Name")]
        public string AuthorityName { get; set; }

        public string OldAuthorityLink { get; set; }

        public string OldAuthorityName { get; set; }

        public int ExistData { get; set; }

        public string UserName { get; set; }
    }
}

Controllers/AuthorityController.cs
using BLMS.Context;
using BLMS.Custom_Attributes;
using BLMS.CustomAttributes;
using BLMS.Enums;
using BLMS.Models.SOP;
using BLMS.v2.Context;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using static BLMS.Helper;

namespace BLMS.Controllers
{
    public class AuthorityController : Controller
    {
        readonly SOPDBContext dbContext = new SOPDBContext();
        readonly AuditLogDbContext logController = new AuditLogDbContext();
         

        #region GRIDVIEW
        [Authorize(Roles.ADMINISTRATOR, Roles.BUSINESS_UNIT, Roles.PIC)]
        [Authorize(AccessLevel.ADMINISTRATION, AccessLevel.HQ, AccessLevel.SITE)]
        public ActionResult Index()
        {
            List<Authority> authorityList = dbContext.AuthorityGetAll().ToList();

            if (TempData["createMessage"] != null)
            {
                ViewBag.Alert = AlertNotification.ShowAlert(Alert.Success, TempData["createMessage"].ToString());
            }
            else if (TempData["editMessage"] != null)
            {
                ViewBag.Alert = AlertNotification.ShowAlert(Alert.Success, TempData["editMessage"].ToString());
            }
            else if (TempData["deleteMessage"] != null)
            {
                ViewBag.Alert = AlertNotification.ShowAlert(Alert.Delete, TempData["deleteMessage"].ToString());
            }

            return View(authorityList);
        }
        #endregion

        #region CREATE
        [NoDirectAccess]
        public ActionResult Create()
        {
            return View();
        }

        // POST: BusinessDivController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind] Authority authority)
        {
            string UserName = HttpContext.User.Identity.Name;

            try
            {
               

                if (string.IsNullOrEmpty(authority.AuthorityName) && string.IsNullOrEmpty(authority.AuthorityLink))
                {
                    ModelState.AddModelError("", "Please type Authority Name");
                    ModelState.AddModelError("", "Please type Authority Link");
                    ViewBag.Alert = AlertNotification.ShowAlertAll(Alert.WarningTwo, "Please type Authority Name", "Please type Authority Link", "", "");
                }
                else if (string.IsNullOrEmpty(authority.AuthorityName))
                {
                    ModelState.AddModelError("", "Please type Authority Name");
                    ViewBag.Alert = AlertNotification.ShowAlert(Alert.Warning, "Please type Authority Name");
                }
                else if (string.IsNullOrEmpty(authority.AuthorityLink))
                {
                    ModelState.AddModelError("", "Please type Authority Link");
                    ViewBag.Alert = AlertNotification.ShowAlert(Alert.Warning, "Please type Authority Link");
                }
                else if (ModelState.IsValid)
                {
                    string AuthorityName = authority.AuthorityName;

                    Authority checkAuthority = dbContext.CheckAuthorityByName(AuthorityName);

                    if (checkAuthority.ExistData == 1)
                    {
                        ViewBag.Alert = AlertNotification.ShowAlert(Alert.Danger, string.Format("{0} already existed in BLMS database!", AuthorityName));
                        return View(authority);
                    }
                    else
                    {
                        dbContext.AddAuthority(authority, UserName);
                        TempData["createMessage"] = string.Format("{0} has been successfully created!", AuthorityName);
                        return RedirectToAction("Index");
                    }
                }

                return View(authority);
            }
            catch(Exception ex)
            {
                string path = "AUTHORITY";

                System.Diagnostics.StackTrace trace = new System.Diagnostics.StackTrace(ex, true);

                string msg = ex.Message;
                string method = trace.GetFrame((trace.FrameCount - 1)).GetMethod().ToString();
                Int32 lineNumber = trace.GetFrame((trace.FrameCount - 1)).GetFileLineNumber();

                logController.AddErrorLog(path, method, lineNumber, msg, UserName);

                return View(); 
            }
        }
        #endregion

        #region EDIT
        [NoDirectAccess]
        public ActionResult Edit(int id)
        {
            Authority authority = dbContext.GetAuthorityByID(id);

            if (authority == null)
            {
                return NotFound();
            }

            return View(authority);
        }

        // POST: BusinessDivController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, [Bind] Authority authority)
        {
            string UserName = HttpContext.User.Identity.Name;

            try
            {
                

                if (string.IsNullOrEmpty(authority.AuthorityName) && string.IsNullOrEmpty(authority.AuthorityLink))
                {
                    ModelState.AddModelError("", "Please type Authority Name");
                    ModelState.AddModelError("", "Please type Authority Link");
                    ViewBag.Alert = AlertNotification.ShowAlertAll(Alert.WarningTwo, "Please type Authority Name", "Please type Authority Link", "", "");
                }
                else if (string.IsNullOrEmpty(authority.AuthorityName))
                {
                    ModelState.AddModelError("", "Please type Authority Name");
                    ViewBag.Alert = AlertNotification.ShowAlert(Alert.Warning, "Please type Authority Name");
                }
                else if (string.IsNullOrEmpty(authority.AuthorityLink))
                {
                    ModelState.AddModelError("", "Please type Authority Link");
                    ViewBag.Alert = AlertNotification.ShowAlert(Alert.Warning, "Please type Authority Link");
                }
                else if (ModelState.IsValid)
                {
                    Authority checkAuthority= dbContext.CheckAuthorityByName(authority.AuthorityName);

                    if (checkAuthority.ExistData == 1 && authority.AuthorityName == authority.OldAuthorityName && authority.AuthorityLink == authority.OldAuthorityLink)
                    {
                        return RedirectToAction("Index");
                    }
                    else if (checkAuthority.ExistData == 1 && authority.AuthorityName != authority.OldAuthorityName)
                    {
                        ViewBag.Alert = AlertNotification.ShowAlert(Alert.Danger, string.Format("{0} already existed in BLMS database!", authority.AuthorityName));
                        return View(authority);
                    }
                    if (checkAuthority.ExistData == 1 && (authority.AuthorityName != authority.OldAuthorityName | authority.AuthorityLink == authority.OldAuthorityLink))
                    {
                        dbContext.EditAuthority(authority, UserName);
                        TempData["editMessage"] = string.Format("{0} has been successfully edited!", authority.AuthorityName);
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        dbContext.EditAuthority(authority, UserName);
                        TempData["editMessage"] = string.Format("{0} has been successfully edited!", authority.AuthorityName);
                        return RedirectToAction("Index");
                    }
                }

                return View(dbContext);
            }
            catch(Exception ex)
            {
                string path = "AUTHORITY";

                System.Diagnostics.StackTrace trace = new System.Diagnostics.StackTrace(ex, true);

                string msg = ex.Message;
                string method = trace.GetFrame((trace.FrameCount - 1)).GetMethod().ToString();
                Int32 lineNumber = trace.GetFrame((trace.FrameCount - 1)).GetFileLineNumber();

                logController.AddErrorLog(path, method, lineNumber, msg, UserName);

                return View();
            }
        }
        #endregion

        #region DELETE
        public JsonResult Delete(int Id)
        {
            string UserName = User.Identity.Name;

            try
            {
                Authority authority = dbContext.GetAuthorityByID(Id);

                dbContext.DeleteAuthority(Id, authority.AuthorityName, UserName);
                TempData["deleteMessage"] = string.Format("{0} has been deleted from BLMS database!", authority.AuthorityName);

                return Json(new { status = "Success" });
            }
            catch(Exception ex)
            {
                string path = "AUTHORITY";

                System.Diagnostics.StackTrace trace = new System.Diagnostics.StackTrace(ex, true);

                string msg = ex.Message;
                string method = trace.GetFrame((trace.FrameCount - 1)).GetMethod().ToString();
                Int32 lineNumber = trace.GetFrame((trace.FrameCount - 1)).GetFileLineNumber();

                logController.AddErrorLog(path, method, lineNumber, msg, UserName);


                return Json(new { status = "Fail" });
            }
        }
        #endregion
    }
}

Views/Authority/Create.cshtml
@model BLMS.Models.SOP.Authority

@{
    ViewData["Title"] = "Create Authority Link";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="mt-md-4 pt-md-2 mb-5 pb-5">
    <!-- Grid row -->
    <div class="row">

        <!-- Grid column -->
        <div class="col-md-12">
            <div class="card card-cascade cascading-admin-card user-card">
                <!-- Card Data -->
                <div class="admin-up d-flex justify-content-start">
                    <i class="fas fa fa-link info-color py-4 mr-3 z-depth-2"></i>
                    <div class="data">
                        <h5 class="font-weight-bold dark-grey-text">
                            Create Authority Link
                        </h5>
                    </div>
                </div>
                <!-- Card Data -->
                <!-- Card content -->
                <div class="card-body card-body-cascade">
                    <!-- Grid row -->
                    <div class="row">
                        <div class="col-lg-12">
                            <form asp-action="Create" autocomplete="off">
                                <div class="row">
                                    <!-- Grid column -->
                                    <div class="col-md-12">
                                        <div id="alert" class="form-group">
                                            @Html.Raw(@ViewBag.Alert)
                                        </div>
                                    </div>
                                    <!-- Grid column -->
                                </div>

                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="md-form form-sm mb-0">
                                            <input asp-for="AuthorityName" onkeyup="this.value=this.value.toUpperCase()" class="form-control" placeholder="Type New Authority Name">
                                            <label asp-for="AuthorityName" class="control-label"><span style="color:red;">*</span> Authority Name</label>
                                            <span asp-validation-for="AuthorityName" class="text-danger text-sm"></span>
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="md-form form-sm mb-0">
                                            <textarea asp-for="AuthorityLink" rows="3" class="md-textarea form-control" placeholder="Type New Authority Link"></textarea>
                                            <label asp-for="AuthorityLink" class="control-label"><span style="color:red;">*</span> Authority Link</label>
                                            <span asp-validation-for="AuthorityLink" class="text-danger text-sm"></span>
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <input type="submit" value="Create" class="btn btn-outline-primary waves-effect" />
                                            <a asp-action="Index" class="btn btn-outline-success waves-effect">Back</a>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Authority/Edit.cshtml
@model BLMS.Models.SOP.Authority

@{
    ViewData["Title"] = "Create Authority Link";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="mt-md-4 pt-md-2 mb-5 pb-5">
    <!-- Grid row -->
    <div class="row">

        <!-- Grid column -->
        <div class="col-md-12">
            <div class="card card-cascade cascading-admin-card user-card">
                <!-- Card Data -->
                <div class="admin-up d-flex justify-content-start">
                    <i class="fas fa fa-link info-color py-4 mr-3 z-depth-2"></i>
                    <div class="data">
                        <h5 class="font-weight-bold dark-grey-text">
                            Create Authority Link
                        </h5>
                    </div>
                </div>
                <!-- Card Data -->
                <!-- Card content -->
                <div class="card-body card-body-cascade">
                    <!-- Grid row -->
                    <div class="row">
                        <div class="col-lg-12">
                            <form asp-action="Edit" autocomplete="off">
                                <div class="row">
                                    <!-- Grid column -->
                                    <div class="col-md-12">
                                        <div id="alert" class="form-group">
                                            @Html.Raw(@ViewBag.Alert)
                                        </div>
                                    </div>
                                    <!-- Grid column -->
                                </div>

                                <div class="row">
                                    <div class="col-md-12" hidden>
                                        <div class="md-form form-sm mb-0">
                                            <input asp-for="AuthorityID" class="form-control">
                                            <label asp-for="AuthorityID" class="control-label"><span style="color:red;">*</span> Authority ID</label>
                                            <span asp-validation-for="AuthorityID" class="text-danger text-sm"></span>
                                        </div>
                                    </div>

                                    <div class="col-md-12" hidden>
                                        <div class="md-form form-sm mb-0">
                                            <input asp-for="OldAuthorityName" class="form-control">
                                            <label asp-for="OldAuthorityName" class="control-label"><span style="color:red;">*</span> Old Authority Name</label>
                                            <span asp-validation-for="OldAuthorityName" class="text-danger text-sm"></span>
                                        </div>
                                    </div>

                                    <div class="col-md-12" hidden>
                                        <div class="md-form form-sm mb-0">
                                            <input asp-for="OldAuthorityLink" class="form-control">
                                            <label asp-for="OldAuthorityLink" class="control-label"><span style="color:red;">*</span> Old Authority Link</label>
                                            <span asp-validation-for="OldAuthorityLink" class="text-danger text-sm"></span>
                                        </div>
                                    </div>

                                    <div class="col-md-12">
                                        <div class="md-form form-sm mb-0">
                                            <input asp-for="AuthorityName" onkeyup="this.value=this.value.toUpperCase()" class="form-control" placeholder="Type New Authority Name">
                                            <label asp-for="AuthorityName" class="control-label"><span style="color:red;">*</span> Authority Name</label>
                                            <span asp-validation-for="AuthorityName" class="text-danger text-sm"></span>
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="md-form form-sm mb-0">
                                            <textarea asp-for="AuthorityLink" rows="3" class="md-textarea form-control" placeholder="Type New Authority Link"></textarea>
                                            <label asp-for="AuthorityLink" class="control-label"><span style="color:red;">*</span> Authority Link</label>
                                            <span asp-validation-for="AuthorityLink" class="text-danger text-sm"></span>
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <input type="submit" value="Edit" class="btn btn-outline-primary waves-effect" />
                                            <a asp-action="Index" class="btn btn-outline-success waves-effect">Back</a>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Authority/Index.cshtml
@model IEnumerable<BLMS.Models.SOP.Authority>

@{
    ViewData["Title"] = "Authority Link";
}

<section class="section align-baseline">
    <!-- Grid row -->
    <div class="row">

        <!-- Grid column -->
        <div class="col-md-12">
            <div class="card card-cascade cascading-admin-card user-card">
                <!-- Card Data -->
                <div class="admin-up d-flex justify-content-start">
                    <i class="fas fa fa-link info-color py-4 mr-3 z-depth-2"></i>
                    <div class="data">
                        <h5 class="font-weight-bold dark-grey-text">
                            Authority Link
                        </h5>
                    </div>
                </div>
                <!-- Card Data -->
                <!-- Card content -->
                <div class="card-body card-body-cascade">
                    <!-- Grid row -->
                    <div class="row">
                        <div class="col-lg-12">
                            <div id="alert" class="form-group">
                                @Html.Raw(@ViewBag.Alert)
                            </div>

                            <div class="table table-wrapper table-responsive-sm" style="width:100%">
                                <!--Table-->
                                <table id="AuthorityLink" class="table table-hover mb-0">
                                    <!-- Table head -->
                                    <thead>
                                        <tr>
                                            <th class="text-sm font-weight-bold align-text-top col-md-3">
                                                @Html.DisplayNameFor(model => model.AuthorityName)
                                            </th>
                                            <th class="text-sm font-weight-bold align-text-top col-md-7">
                                                @Html.DisplayNameFor(model => model.AuthorityLink)
                                            </th>
                                            <th class="text-sm font-weight-bold align-text-top col-md-2 text-center">Action</th>
                                        </tr>
                                    </thead>
                                    <!-- Table head -->
                                    <!-- Table body -->
                                    <tbody>
                                        @foreach (var item in Model)
                                        {
                                            <tr id="row_@item.AuthorityID">
                                                <td class="text-sm align-text-top">
                                                    @Html.DisplayFor(modelItem => item.AuthorityName)
                                                </td>
                                                <td class="text-sm font-weight-bold align-text-top text-break">
                                                    <a href="@item.AuthorityLink" target="_blanK">@Html.DisplayFor(modelItem => item.AuthorityLink)</a>
                                                </td>
                                                <td class="text-center">
                                                    <a class="btn btn-outline-primary btn-rounded btn-sm px-2" title="Edit" href="@Url.Action("Edit", "Authority", new {id=item.AuthorityID})">
                                                        <i class="fas fa-pencil-alt mt-0"></i>
                                                    </a>
                                                    <a class="btn btn-outline-danger btn-rounded btn-sm px-2" title="Delete" href="#" onclick="ConfirmDelete(@item.AuthorityID)">
                                                        <i class="fas fa-trash-alt mt-0"></i>
                                                    </a>
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                    <!-- Table body -->
                                </table>
                                <!-- Table -->
                                <!--Delete bootstrap confirmation box-->
                                <div class="modal fade top" id="delete-conformation" aria-labelledby="delete-conformation" aria-hidden="true" tabindex="-1" role="dialog">
                                    <div class="modal-dialog modal-frame modal-top modal-notify modal-danger">
                                        <div class="modal-content">
                                            <div class="modal-header flex-column">
                                                <div class="icon-box">
                                                    <i class="material-icons">&#xE5CD;</i>
                                                </div>
                                                <h4 class="modal-title w-100 font-weight-bolder text-center text-white">DELETE AUTHORITY LINK?</h4>
                                                <br />
                                                <p class="mb-1 align-self-sm-center text-white" style="color: red;"><i class="fas fa-exclamation-circle"></i> The saved data will be permanently deleted from BLMS database.</p>
                                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                            </div>
                                            <div class="modal-footer justify-content-center">
                                                <button type="button" class="btn btn-outline-info waves-effect" data-dismiss="modal">Cancel</button>
                                                <a href="#" class="btn btn-outline-danger waves-effect" onclick="DeleteAuthority()"><i class="far fa fa-eraser ml-1 text-black"></i> Delete</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <a asp-action="Create" class="btn btn-outline-success btn-block text-white text-sm font-weight-bold"><i class="far fa fa-plus ml-1 text-black"></i> Create Authority Link</a>

                                @*hidden field for storing current employeeId*@
                                <input type="hidden" id="hidAuthorityId" />
                            </div>
                        </div>
                    </div>
                    <!-- Grid row -->
                </div>
                <!-- Card content -->
            </div>
        </div>
    </div>
</section>

@section Scripts {
    <script>
        var ConfirmDelete = function (AuthorityId) {

            $("#hidAuthorityId").val(AuthorityId);
            $("#delete-conformation").modal('show');
        }

        var DeleteAuthority = function () {
            var AuthorityId = $("#hidAuthorityId").val();

            $.ajax({
                type: "POST",
                url: '@Url.Action("Delete", "Authority")',
                dataType: "json",
                data: { Id: AuthorityId },
                success: function (result) {
                    $("#delete-conformation").modal("hide");
                    $("#row_" + AuthorityId).remove();
                    window.location.href =  '@Url.Action("Index", "Authority")'
                }
            })
        }
    </script>

    <script>
        $(document).ready(function () {
            $('#AuthorityLink').DataTable();
            $('.dataTables_length').addClass('bs-select');
        });

        //auto hide viewbag.alert
        $(document).ready(function () {
            setTimeout(function () {
                $("#alert").fadeOut();
            }, 3000);
        });
    </script>

    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}